### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by jpotier** [FreeRDP/FreeRDP-old#13]
Hi !

I had to cope with some unchecked dependencies when I built freerdp, configure script missed missing :
- `Xv.h` (in package `x11proto-video-dev`), and
- `Xvlib.h` (in package `libxv-dev`)

which are _required_ to build. After adding the missing packages on my system (debian-testing) it ran fine.
## 

**MPO**

**Comment by otavio** [comment]
I fixes this build issue on 18e9d76c1936b6efc4ab6d91d127be20173ec903. Please try to reproduce the issue again using this revision.

**Comment by jpotier** [comment]
Issue is not reproduced after today's fix.
Thanks
