### ISSUE TITLE
.settings directory on SCM

### ISSUE THREAD

**Issue by otavio** [FreeRDP/FreeRDP-old#34]
There's a .settings used by an IDE inside of SCM.

It would be better to drop it since it is not a common standard and people can use many different IDEs.

@awakecoding I am assigning it to you since it camed with a commit done by you.

**Comment by awakecoding** [comment]
@otavio: I'll clean it up, it shouldn't have been there in the first place

**Comment by otavio** [comment]
Dropped at 1a6184d3fe698fae9779d6b14e230bb8578dc59e
