### ISSUE TITLE
Unknown keycodes 129 (numeric '.') and 97 ('?' or '/')

### ISSUE THREAD

**Issue by eduardobeloni** [FreeRDP/FreeRDP-old#39]
I've got the following output for such ordinary keys:

```
xf_kb_send_key: unknown key down keycode=97 (X keysym=0x002F)
xf_kb_send_key: unknown key up keycode=97 (X keysym=0x002F)
xf_kb_send_key: unknown key down keycode=129 (X keysym=0xFFAE)
xf_kb_send_key: unknown key up keycode=129 (X keysym=0xFFAE)
```

This is the keyboard layout ID: -k 0x00010416, which I got from: 0x00010416 Portuguese (Brazilian ABNT2)
Setting the ID or not, the result is the same though

**Comment by kiilerix** [comment]
On 06/10/2011 10:04 PM, beloni wrote:

> I've got the following output for such ordinary keys:
> 
> ```
> xf_kb_send_key: unknown key down keycode=97 (X keysym=0x002F)
> xf_kb_send_key: unknown key up keycode=97 (X keysym=0x002F)
> xf_kb_send_key: unknown key down keycode=129 (X keysym=0xFFAE)
> xf_kb_send_key: unknown key up keycode=129 (X keysym=0xFFAE)
> ```
> 
> This is the keyboard layout ID: -k 0x00010416, which I got from: 0x00010416   Portuguese (Brazilian ABNT2)
> Setting the ID or not, the result is the same though

That is with xfreerdp?

Is that with --with-xkbfile ?

If so: Please post the output with --with-debug-x11-kbd .

/Mads

**Comment by eduardobeloni** [comment]
Using --with-xkbfile or not, the result is the same. Apparently those keys aren't registered in virtualKeyboard (libfreerdp-kbd/keyboard.h), because they weren't found:

```
DBG_KBD init_keycodes_from_xkb (135): X key code  97 has keyname AB11 -> ??? - not found
DBG_KBD init_keycodes_from_xkb (135): X key code 129 has keyname I129 -> ??? - not found
```

I think I've just got to add the proper entry in the virtualKeyboard table from keyboard.h. So I'm trying to figure out how are done all these X keycode to RDP keycode conversions, which are black magic for me so far...

**Comment by kiilerix** [comment]
beloni wrote, On 06/13/2011 02:27 PM:

> Using --with-xkbfile or not, the result is the same. Apparently those keys aren't registered in virtualKeyboard (libfreerdp-kbd/keyboard.h), because they weren't found:
> 
> ```
> DBG_KBD init_keycodes_from_xkb (135): X key code  97 has keyname AB11 ->  ??? - not found
> DBG_KBD init_keycodes_from_xkb (135): X key code 129 has keyname I129 ->  ??? - not found
> ```
> 
> I think I've just got to add the proper entry in the virtualKeyboard table from keyboard.h. So I'm trying to figure out how are done all these X keycode to RDP keycode conversions, which are black magic for me so far...

Yes, the keyboard handling is messy. I made it more messy by replacing 
most of it with (IMHO) simpler and more correct code that avoids using 
the actual client side keyboard layout when the actual layout processing 
is done on the server side. The old code is however apparently needed 
for some platforms.

Note that when you are using xkbfile then -k is _only_ used for telling 
the server which layout to use.

It is thus related to the "physical" wiring of your physical keyboard. 
The numeric '.' key is usually known by X as KPDL (for delimiter) but in 
your case X reports a more anonymous name. Is they keyboard special in 
any way?

Do you know which RDP "scan codes" these keys should map to? Could you 
try with mstsc.exe and either wireshark or xrdp?

/Mads

**Comment by eduardobeloni** [comment]
> Do you know which RDP "scan codes" these keys should map to? Could you try with mstsc.exe and either wireshark or xrdp?

Yeah, thats exacly the point: figure out what are the right RDP scan codes for these keys...

**Comment by kiilerix** [comment]
beloni wrote, On 06/13/2011 04:11 PM:

> > Do you know which RDP "scan codes" these keys should map to? Could you try with mstsc.exe and either wireshark or xrdp?
> > Yeah, thats exacly the point: figure out what are the right RDP scan codes for these keys...

The RDP scan codes are often similar to the windows keyboard event 
scancodes, so wfreerdp (or some windows tool) might give the right 
answer too.

/Mads

**Comment by eduardobeloni** [comment]
Hello Mads

Thanks very much for the help. I've just pushed the fix.
