### ISSUE TITLE
Client fails with pa_operation_get_state() with no sound card

### ISSUE THREAD

**Issue by gadiromm** [FreeRDP/FreeRDP-old#47]
When a client is set to enable audio redirection but lacks the sound card hardware to do so (for example, in a virtual machine), the client will log in but then die after log in when the audio is accessed.

The error is: 

Assertion 'o' failed at pulse/operation.c:128, function pa_operation_get_state(). Aborted.

**Comment by llyzs** [comment]
the crash was fixed in 1.0

**Comment by chihchun** [comment]
Fixed crashing issue in https://github.com/FreeRDP/FreeRDP-1.0/commit/bd5fb5c62a77df2d3686245efeb8f5fe727521e8
