### ISSUE TITLE
Unable to connect to Virtualbox RDP server

### ISSUE THREAD

**Issue by helgef** [FreeRDP/FreeRDP-old#66]
commit a0a25a61d89018c3ca7d551f36f33d45b90249d5

Virtualbox implements its own RDP server displaying its guest OS. FreeRDP does not work with this server. MS Remote Desktop client (for mac) works fine.

Show connected, but never displays:

Helges-MacBook-Air:X11 helge$ ./xfreerdp 192.168.1.150
Warning xf_GetWindowProperty (104): Property 294 does not exist
connected to 192.168.1.150:3389

**Comment by otavio** [comment]
Please, report this against FreeRDP/FreeRDP project.

Closing the issue as it is not valid to this tree.
